### PR TITLE
Fix report when output register anontation is missing

### LINKED ISSUE #814: [test_binemit] Signal when the test lacks register constraints
When writing a binemit test, if we test the generation of an assembly instruction which outputs registers (GPR or FPR), and we forget about setting the output register constraint, then test_binemit doesn't find any encodings, because constraints can never be satisfied on unknown value locations. Instead, we should report that an output register annotation is missing.

### PR DESCRIPTION
**Pull request by Y-Nak**
Hi, This PR resolves #814
r? @bnjbvr

- [x] This has been discussed in issue #814
- [x] Fix issue #814 and a little bit of refactoring.
- [ ] This PR contains test cases, if meaningful.
- [ ] A reviewer from the core maintainer team has been assigned for this PR.
  If you don't know who could review this, please indicate so and/or ping
  `bnjbvr`. The list of suggested reviewers on the right can help you.

### CODE REVIEW

File: cranelift-filetests/src/test_binemit.rs [hunk 1]
```diff
@@ -337,3 +316,41 @@ impl SubTest for TestBinEmit {
         Ok(())
     }
 }
+
+// validate registers/stack slots are correctly annotated
```
Comment (bjorn3) [inline cranelift-filetests/src/test_binemit.rs]: Please use a tripple slash here.

**Comment by Y-Nak** [comment]
OK.
And really sorry I forgot branching from master.
Can I close this PR and recreate PR?

**Comment by bjorn3** [comment]
There are no conflicts between master and this PR, so it isn't a problem that this isn't based on the latest commit on master.

**Comment by Y-Nak** [comment]
OK, thanks.
I fixed.

File: cranelift-filetests/src/test_binemit.rs [hunk 2]
```diff
@@ -337,3 +316,41 @@ impl SubTest for TestBinEmit {
         Ok(())
     }
 }
+
+/// validate registers/stack slots are correctly annotated
```
Comment (bnjbvr) [inline cranelift-filetests/src/test_binemit.rs]: nit: Please capitalize the first letter, and end sentence with a dot.

File: cranelift-filetests/src/test_binemit.rs [hunk 3]
```diff
@@ -337,3 +316,41 @@ impl SubTest for TestBinEmit {
...
+    {
+        Err(format!(
+            "Need register/stack slot annotation for {} in {}",
+            v,
+            func.dfg.display_inst(inst, isa)
+        ))
+    } else if validate_args {
+        if let Some(&v) = func
+            .dfg
+            .inst_args(inst)
```
Comment (bnjbvr) [inline cranelift-filetests/src/test_binemit.rs]: Alternatively, to reduce code duplication, could the function either look at args *or* results, but not both at the same time? In the second call site, it would be called twice instead of once, which is fine.

Then you can do something like `let values = if validate_args { func.dfg.inst_args(inst) } else { func.dfg.inst_results(inst) };` and check the values' locations.

File: cranelift-filetests/src/test_binemit.rs [hunk 4]
```diff
@@ -337,3 +316,41 @@ impl SubTest for TestBinEmit {
         Ok(())
     }
 }
+
+/// validate registers/stack slots are correctly annotated
+fn validate_annotation(
```
Comment (bnjbvr) [inline cranelift-filetests/src/test_binemit.rs]: Can this be named `validate_location_annotations` to be more complete, please?
